version: "3.4"

services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      ERROR_ON_UNWRITTEN_DATA: "true"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  resource:
    image: semtech/mu-cl-resources:1.22.2
    links:
      - database:database
    volumes:
      - ./config/resources:/config
  frontend:
    image: lblod/frontend-centrale-vindplaats:0.3.1-fastboot # fixme, quick and dirty hack
    environment:
      EMBER_METIS_BASE_URL: "http://data.lblod.info/"
    links:
      - identifier:backend
    restart: always
  consumer:
    image: redpencil/ldes-consumer
    environment:
      CRON_PATTERN: "*/10 * * * * *"
      LDES_STREAM: https://dev-vlag.roadsigns.lblod.info/ldes-mow-register
      LDES_ENDPOINT_VIEW: https://dev-vlag.roadsigns.lblod.info/ldes-mow-register/1
      MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/ldes"
  make-object:
    image: lblod/ldes-make-object-service
    links:
      - database:database
  # Metis
  uri-info:
    image: redpencil/mu-uri-info-service:0.2.1
  resource-labels-cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource-labels:backend
  resource-labels:
    image: lblod/resource-label-service:0.3.2
